<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>FreightWing</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Novolis.Audio.Core" />
    <PackageReference Include="Novolis.Audio.Effects" />
    <PackageReference Include="Novolis.Audio.Playback" />
    <PackageReference Include="Novolis.Game.MenuFlows" />
    <PackageReference Include="Novolis.MachineLearning.Neural" />
    <PackageReference Include="Novolis.Simulation.SpaceCombat" />
    <PackageReference Include="Novolis.Simulation.View" />
    <PackageReference Include="Novolis.Raylib">
      <ExcludeAssets>buildTransitive</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Novolis.Raylib.Game" />
    <PackageReference Include="Novolis.Raylib.Bindings" />
    <PackageReference Include="Novolis.Raylib.Runtime" />

    <ProjectReference Include="..\..\shared\Novolis.Lab.SpaceCombat\Novolis.Lab.SpaceCombat.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Content\**\*" CopyToOutputDirectory="PreserveNewest" Link="Content\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
