<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <OutputType>Exe</OutputType>
    <RootNamespace>Novolis.Lab.MapProviders</RootNamespace>
    <AssemblyName>Novolis.MapProvidersLab</AssemblyName>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <ApplicationTitle>Novolis Map Providers</ApplicationTitle>
    <ApplicationId>dev.novolis.mapproviderslab</ApplicationId>
    <ApplicationDisplayVersion>$(NovolisPlatformVersion)</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">win-x64</RuntimeIdentifier>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <WindowsPackageType>None</WindowsPackageType>
    <AppxPackageSigningEnabled>false</AppxPackageSigningEnabled>
    <PublishReadyToRun>false</PublishReadyToRun>
  </PropertyGroup>
  <ItemGroup>
    <MauiIcon Include="Resources\AppIcon\appicon.svg" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Controls" />
    <LibraryReference Include="Novolis.IO.Maps" />
    <LibraryReference Include="Novolis.Maui.GraphicalProfile" />
    <LibraryReference Include="Novolis.Maui.Map" />
  </ItemGroup>
</Project>
