<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>RenderingAvalonia</RootNamespace>
    <IsPackable>false</IsPackable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Novolis.Avalonia.Rendering" />
    <PackageReference Include="Novolis.Avalonia.Raylib" />
    <PackageReference Include="Novolis.Math.Geometry" />
    <PackageReference Include="Novolis.Math.Topology" />
    <PackageReference Include="Novolis.Rendering.TwoD" />
    <PackageReference Include="Novolis.Raylib">
      <ExcludeAssets>buildTransitive</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Novolis.Raylib.Abstractions" />
    <PackageReference Include="Novolis.Raylib.Runtime" />
  </ItemGroup>
</Project>
