<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>AssetStudioLab.Unit</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <NovolisGraphicalProfile>false</NovolisGraphicalProfile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" />
    <ProjectReference Include="..\..\AssetStudioLab.Core\AssetStudioLab.Core.csproj" />
  </ItemGroup>
</Project>
