<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>Novolis.Lab.TwoD</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <LibraryReference Include="Novolis.Math.Arrays" />
    <LibraryReference Include="Novolis.Math.Geometry" />
    <LibraryReference Include="Novolis.Math.Topology" />
    <LibraryReference Include="Novolis.Rendering.TwoD" />
  </ItemGroup>
</Project>
