<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>CursorRemote.Desktop</RootNamespace>
    <AssemblyName>CursorRemote</AssemblyName>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CursorRemote\CursorRemote.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Avalonia.Desktop" />
    <LibraryReference Include="Novolis.Avalonia.GraphicalProfile" />
    <LibraryReference Include="Novolis.Avalonia.Mobile.Desktop" />
  </ItemGroup>
</Project>
