<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <RootNamespace>HelloRaygui</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Novolis.Raylib">
      <ExcludeAssets>buildTransitive</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Novolis.Raylib.Game" />
    <PackageReference Include="Novolis.Raylib.Raygui" />
    <PackageReference Include="Novolis.Raylib.Runtime" />
    <PackageReference Include="Novolis.Raylib.Bindings" />
  </ItemGroup>
</Project>
