<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NovolisGraphicalProfile>true</NovolisGraphicalProfile>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-android</TargetFramework>
    <SupportedOSPlatformVersion>23</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ApplicationId>com.novolis.spacefleetsurveyteam</ApplicationId>
    <ApplicationDisplayVersion>0.1.0</ApplicationDisplayVersion>
    <ApplicationVersion Condition="'$(NovolisAndroidVersionCode)' != ''">$(NovolisAndroidVersionCode)</ApplicationVersion>
    <ApplicationVersion Condition="'$(ApplicationVersion)' == ''">1</ApplicationVersion>
    <RootNamespace>SpaceFleetSurveyTeam.Android</RootNamespace>
    <AssemblyName>SpaceFleetSurveyTeam.Android</AssemblyName>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SpaceFleetSurveyTeam\SpaceFleetSurveyTeam.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Android" />
    <LibraryReference Include="Novolis.Avalonia.GraphicalProfile" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <LibraryReference Include="Novolis.Avalonia.Mobile.Android" />
    <PackageReference Include="Xamarin.AndroidX.AppCompat" />
    <PackageReference Include="Xamarin.AndroidX.Core.SplashScreen" />
  </ItemGroup>
</Project>
