<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>NeuralRacing</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <LibraryReference Include="Novolis.MachineLearning.Neural" />
    <LibraryReference Include="Novolis.Simulation.Racing" />
  </ItemGroup>
</Project>
