<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>SilkTwoDHello</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <LibraryReference Include="Novolis.Rendering.TwoD" />
    <LibraryReference Include="Novolis.Rendering.Backends.TwoD.Silk" />
    <LibraryReference Include="Novolis.Rendering.Presentation.Abstractions" />
    <LibraryReference Include="Novolis.Math.Geometry" />
    <LibraryReference Include="Novolis.Math.Topology" />
  </ItemGroup>
</Project>
