<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>PlatformerHop</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Novolis.Raylib">
      <ExcludeAssets>buildTransitive</ExcludeAssets>
    </PackageReference>
    <LibraryReference Include="Novolis.Math.Arrays" />
    <LibraryReference Include="Novolis.Simulation.Kinematics" />
    <LibraryReference Include="Novolis.Simulation.View" />
  </ItemGroup>
</Project>
