<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <RootNamespace>HelloCapture</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Novolis.Raylib">
      <ExcludeAssets>buildTransitive</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Novolis.Raylib.Abstractions" />
    <PackageReference Include="Novolis.Raylib.Capture" />
    <PackageReference Include="Novolis.Raylib.Runtime" />
    <PackageReference Include="Novolis.Raylib.Bindings" />
  </ItemGroup>
</Project>
