<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>RandoriFight</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Novolis.Raylib">
      <ExcludeAssets>buildTransitive</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Novolis.Raylib.Game" />
    <PackageReference Include="Novolis.Raylib.Bindings" />
    <PackageReference Include="Novolis.Simulation.View" />
    <PackageReference Include="Novolis.Simulation.Humanoid" />
  </ItemGroup>
</Project>
