<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>PulseStrip.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" />
    <LibraryReference Include="Novolis.MachineLearning.Neural" />
    <LibraryReference Include="Novolis.MachineLearning.Neural.Abstractions" />
    <LibraryReference Include="Novolis.Simulation.Racing" />
    <ProjectReference Include="..\PulseStrip.Core\PulseStrip.Core.csproj" />
  </ItemGroup>
</Project>
