<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ArtillerySimulator</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Novolis.Raylib" />
    <PackageReference Include="Novolis.Physics.Ballistics" />
    <PackageReference Include="Novolis.Physics.Collision.Simple" />
    <PackageReference Include="Novolis.Simulation.World" />
    <PackageReference Include="Novolis.Simulation.World.Builders" />
    <PackageReference Include="Novolis.Simulation.View" />
  </ItemGroup>
</Project>
